image:
- Visual Studio 2017
- Ubuntu

for:
- matrix:
    only:
    - image: Visual Studio 2017

  build_script:
  - dotnet pack --configuration Release ELFSharp

  test_script:
  - dotnet test --configuration Release Tests

  artifacts:
  - path: '*\bin\Release\*.nupkg'

- matrix:
    only:
    - image: Ubuntu

  build_script:
  - dotnet build --framework netstandard2.0 --configuration Release ELFSharp

  test_script:
  - dotnet test --framework netcoreapp2.0 --configuration Release Tests
